### ISSUE TITLE
Use latest version as version to go : 4.8.?

### ISSUE THREAD

**Issue by wtichelen** [CPDWim/euNTT#10]

**Comment by iayllon** [comment]
Initially, 4.8.2 was defined. Now I see both 4.8.2 and 4.8.5 in parts of the code. We need a decision to communicate to Lot2 as well.

As long as there are no compatibility issues, I'd support using the latest stable version.

**Comment by wtichelen** [comment]
Using latest in images , cm set to 4.8.5
